// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BA3kpdG5WeE913YNnPLZxx4LulcSv70',
    appId: '1:601164812739:web:a1294f8a7b6be2b11c6d76',
    messagingSenderId: '601164812739',
    projectId: 'suddy-ea5fa',
    authDomain: 'suddy-ea5fa.firebaseapp.com',
    storageBucket: 'suddy-ea5fa.appspot.com',
    measurementId: 'G-KFCWC1CWZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-8C_vujttbcsxxr3mYCg3IoC3aa2plw',
    appId: '1:601164812739:android:b647b4cee1a3bbb31c6d76',
    messagingSenderId: '601164812739',
    projectId: 'suddy-ea5fa',
    storageBucket: 'suddy-ea5fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfR9qlmisvV4jLcZkfxH050BGYm4hRJVg',
    appId: '1:601164812739:ios:100cb8992a91a0ba1c6d76',
    messagingSenderId: '601164812739',
    projectId: 'suddy-ea5fa',
    storageBucket: 'suddy-ea5fa.appspot.com',
    iosBundleId: 'com.suddy.suddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfR9qlmisvV4jLcZkfxH050BGYm4hRJVg',
    appId: '1:601164812739:ios:100cb8992a91a0ba1c6d76',
    messagingSenderId: '601164812739',
    projectId: 'suddy-ea5fa',
    storageBucket: 'suddy-ea5fa.appspot.com',
    iosBundleId: 'com.suddy.suddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-BA3kpdG5WeE913YNnPLZxx4LulcSv70',
    appId: '1:601164812739:web:26bcf3c541c5306a1c6d76',
    messagingSenderId: '601164812739',
    projectId: 'suddy-ea5fa',
    authDomain: 'suddy-ea5fa.firebaseapp.com',
    storageBucket: 'suddy-ea5fa.appspot.com',
    measurementId: 'G-NTF2SZ056E',
  );
}
